#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
test -n "$QORE_DB_CONNSTR_ODBC"
module=${QORE_ODBC_BINARY_MODULE:-odbc}
# Fail before the suites if the driver cannot reach the disposable database.
/usr/bin/qore -l "$module" -e 'Datasource db(ENV.QORE_DB_CONNSTR_ODBC); db.open(); db.close();'
for suite in "$1"/*.qtest; do
    timeout 180 /usr/bin/qore -l "$module" "$suite" -v
done
